### ISSUE TITLE
 lua.h: No such file or directory

### ISSUE THREAD

**Issue by swiss-knight** [systemed/tilemaker#184]
Hi, 

I encountered this error while trying to build on Ubuntu 16.04 (4.15.0-117-generic x86_64 GNU/Linux):

```
$ make
g++ -O3 -Wall -Wno-unknown-pragmas -Wno-sign-compare -std=c++11 -pthread  -o src/read_shp.o -c src/read_shp.cpp -I/usr/local/include -isystem ./include -I./src -I/usr/local/include/lua5.1 -I/usr/include/lua5.1
In file included from ./include/read_shp.h:11:0,
                 from src/read_shp.cpp:1:
./include/osm_lua_processing.h:20:18: fatal error: lua.h: No such file or directory
compilation terminated.
Makefile:13: recipe for target 'src/read_shp.o' failed
make: *** [src/read_shp.o] Error 1

```

lua5.2 and liblua5.2-dev are installed instead of 5.1.

Is it possible to make the build agnostic of lua version?

Thanks.

**Comment by systemed** [comment]
You could probably just edit the Makefile to replace the references to 5.1 with 5.2 - try that and let me know how you get on.

**Comment by systemed** [comment]
Fixed in https://github.com/systemed/tilemaker/commit/a2073475f01be3e271c4046e469fd6ef7be45172 . You can even use LuaJIT for extra speed!
