### ISSUE TITLE
error: ‘mmap_files’ was not declared in this scope

### ISSUE THREAD

**Issue by sguilly** [systemed/tilemaker#291]
Ubuntu 20.04.2 LTS : Fail to compile with lastest commit / works well with commit ed2988b79e70d1a932035dd9268491dee8e02346

src/osm_store.cpp: In static member function ‘static void void_mmap_allocator::deallocate(void*, void_mmap_allocator::size_type)’:
src/osm_store.cpp:239:15: error: ‘mmap_files’ was not declared in this scope; did you mean ‘mmap_file’?
  239 |  for(auto &i: mmap_files) {
      |               ^~~~~~~~~~
      |               mmap_file
src/osm_store.cpp: In static member function ‘static void void_mmap_allocator::destroy(void*)’:
src/osm_store.cpp:277:15: error: ‘mmap_files’ was not declared in this scope; did you mean ‘mmap_file’?
  277 |  for(auto &i: mmap_files) {
      |               ^~~~~~~~~~
      |               mmap_file
make: *** [Makefile:82: src/osm_store.o] Error 1

**Comment by systemed** [comment]
Yep, fixed in #290 and will be merged in a few minutes once the CI's run and I've checked it manually :)
